### ISSUE TITLE
File selection not possible for special setup of the FilePathParam

### ISSUE THREAD

**Issue by schatzkn** [UniStuttgart-VISUS/megamol#1038]
When using the "param::FilePathParam::FilePathFlags_::Flag_NoExistenceCheck" flag on creating a FilePathParam, proper selection of a file or folder via GUI is impossible. 

1. Create a module or modify a module to have a FilePathParam.
2. On creation of the FilePathParam set the flags (the second parameter of the constructor) to "param::FilePathParam::FilePathFlags_::Flag_NoExistenceCheck".
3. Upon running MegaMol, try to modify the file path of the created FilePathParam by navigating through the MegaMol-internal file system representation.
4. It should not be possible to select any folder or file via mouse interaction. Instead, the current folder is set to "." and nothing else happens.

**Expected behavior**
It should be possible to select files or folders normally without the unexpected jumping.

**Environment**
 - OS: Windows 11
 - GPU: Nvidia RTX 2080Ti
 - Driver version 511.65

**Comment by braunms** [comment]
It is mandatory to always state whether the FilePathParam should check for a file, directory, or both. You should use the flag Flag_File_ToBeCreated if you want to use the FilePathParam to hold a not existing file, e.g.

Of course, the FilePathParam flag interface should not provide flags that can not be used on their own. I am sorry, this will be fixed in a pull request soon...
