### ISSUE TITLE
Color and Radius for SOME of the Sphere renderers

### ISSUE THREAD

**Issue by reinago** [UniStuttgart-VISUS/megamol#130]
- [ ] run regression before pushing Release 1.3
- [x] SimpleSphere & NGSphere: Color seems to be taken magically from GL state. Probably a driver update from team green broke this. Use an attribute like SimpleGeoSphere does.
- [x] SimpleSphere does not care about radii from TestSphereDataSource. Is this a similar effect?
- [x] Color = None gives arbitrary results for all renderers but Geo. This uses a global color.

use utils\MMPLD\GenTestFiles.pl to reproduce
(run ..\utils\MMPLD\SphereTest.bat from bin)

**Comment by gralkapk** [comment]
Which driver version are you using?

**Comment by braunms** [comment]
With PullRequest #248 for the following test cases some sphere colors are wrong and some spheres are not shown at all. So far, I have no idea since everything works fine for float vertex positions.
- test_xyz_double_int_float.mmpld-NGSphereRenderer
- test_xyz_double_rgb_float.mmpld-NGSphereRenderer
- test_xyz_double_rgba_byte.mmpld-NGSphereRenderer
