### ISSUE TITLE
Jobs get lost

### ISSUE THREAD

**Issue by tobiasrau** [UniStuttgart-VISUS/megamol#337]
Dumping project files via #326 or #332 does not include jobs.
Could cause problems when dumping cluster jobs.

**Comment by reinago** [comment]
That is actually my fault, since the screenshoter also does not include them (where the dump code is from). The problem is that job instances **really** seem to get lost in the running MegaMol, while view instances are collected in the core with a weird mechanism I would propose to completely drop. With lua projects, instances make no sense anymore anyway (-i is not useful). So what about this:

1. Can anyone find a sensible use of instances anywhere? Why would I create 2 instances of anything since they have to be identical anyway? The only thing that comes to mind is multiple copies of a visualization running on multiple displays on one machine, but you can write a for loop in the project for that.
1. We should get rid of Jobs and Instances. They just add a namespace on top which no one actually cares about (correct me if I'm wrong). We could also just nuke the whole weird-ass startup process with temporary graphs and crap. A project is just lua and it goes into the graph in the next frame, same as at runtime.
1. What is the purpose of jobs anyway?
    1. Instancing modules without opening a window, which would be covered as soon as we have MegaMol running continuously instead of exiting (where did that code go btw).
    1. Providing an entry point for headless conversion. That is a problem. But it will still go away as soon as we have GPU-less Views that can take over the jobs of jobs (omg)
1. IF we do this, XML projects need to go away forever (party). Then I'd rather call 1.4 2.0.
