### ISSUE TITLE
Camera breaks when zooming too much

### ISSUE THREAD

**Issue by tobiasrau** [UniStuttgart-VISUS/megamol#468]
I guess there are more problems, but this definetly should not happen.

    Assertion failed: snapshot.frustum_near != snapshot.frustum_far, file megamol/core/include/mmcore/thecam/camera.inl, line 84

**Comment by invor** [comment]
Do we remeber whether this also happens after reseting the view, or only when trying to use zoom at the intial startup location? Because there is this related issue that the camera spawns at the look-at location and since zoom for orbital cameras is really just changing the orbit (i.e. altitude) relative to the current orbit it crashes crashes (cause orbit_altitude =0).

Technically I expected cam_pos != cam_lookat to be an invariant, but it should propably not explode like this anyway...
