### ISSUE TITLE
Configurator Exception with lua string

### ISSUE THREAD

**Issue by moritz-h** [UniStuttgart-VISUS/megamol#478]
Configurator cannot open projects if TableManipulator lua sources contains a `<` char, like for example the default source of the TableManipulator.
Editing and saving is no problem, but then the project cannot be loaded again.

```
System.Xml.XmlException: '<', hexidezimaler Wert 0x3C, ist ein ungültiges Attributszeichen. Zeile 2114, Position 14.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   bei System.Xml.XmlTextReaderImpl.ParseAttributes()
   bei System.Xml.XmlTextReaderImpl.ParseElement()
   bei System.Xml.XmlTextReaderImpl.ParseElementContent()
   bei System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   bei System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   bei System.Xml.XmlDocument.Load(XmlReader reader)
   bei System.Xml.XmlDocument.Load(String filename)
   bei MegaMolConf.Io.ProjectFile.Load(String filename) in C:\Projects\MegaMol\megamol\configurator\MegaMolConf\Io\ProjectFile.cs:Zeile 57.
   bei MegaMolConf.Program.TryLoadRunFile(String path) in C:\Projects\MegaMol\megamol\configurator\MegaMolConf\Program.cs:Zeile 178.
```

**Comment by moritz-h** [comment]
Bug is not only in configurator, also mmconsole.exe is affected and cannot parse the xml

**Comment by straubar** [comment]
There seem to be multiple problems:
- mmprj-files are written without masking characters, such as `<` as `&lt;`. By doing so manually, the project files can be loaded in the configurator and in MegaMol
- mmprj-files with the masked characters can be loaded, however, fail to produce the correct result (without error, but in my case no values arrived at the PCR on the left side of the table manipulator)
- lua-files containing the line `mmSetParamValue("::Project_1::TableManipulator1::script", "")` cannot be loaded in the configurator even with empty initialization string (weird IndexOutOfRangeException)
- lua-files with a multiline string fail to work in MegaMol because multiline strings in LUA have to be either concatenated (`..` at the line end) or enclosed by `[[ ]]` instead of `" "`, which the configurator fails to do (suggestion: always write value strings with `[[ ]]` to be on the safe side). If enclosed by `[[ ]]`, the same example works when starting MegaMol manually using the command line

My minimal example:
```
View2D -> ParallelCoordinatesRenderer -> TableManipulator -> CSVDataSource
                                      -> TransferFunction
                                      -> FlagStorage
```

Default value for the script, just changed a letter in the comment for it to be exposed and written into the project files.

CSV file:
```
Refinement;Triangulation;Labels;Loop
0.019;0;0.078;0.099
0.038;0.001;0.12;0.162
0.079;0.002;0.22;0.307
0.044;0;0.047;0.091
0.044;0;0.048;0.094
0.045;0;0.046;0.093
0.044;0;0.048;0.093
0.045;0;0.012;0.058
0.044;0;0;0.045
```
