### ISSUE TITLE
BoundingBoxRenderer problems

### ISSUE THREAD

**Issue by pramathe** [UniStuttgart-VISUS/megamol#491]
![mmconsole_debug](https://user-images.githubusercontent.com/44464563/70796300-3176d400-1da2-11ea-9e7f-e3c3fad3b4d0.png)

MegaMol immediately closes when calling BoundingBoxRenderer (cf. ..\examples\testspheres.lua).
When switching BoundingBoxRenderer off I can see flying testspheres ...

System: Win 10, x64
compiled with Visual Studio 2019

**Comment by straubar** [comment]
This problem seems to occur if your graphics card does not support OpenGL 4.5+, which is needed for `glCreateBuffer`. See [https://community.khronos.org/t/glcreatebuffers-access-violation-exception-glfw-glew/75590](https://community.khronos.org/t/glcreatebuffers-access-violation-exception-glfw-glew/75590) and [https://stackoverflow.com/questions/46633617/access-violation-error-when-using-glcreatebuffers](https://stackoverflow.com/questions/46633617/access-violation-error-when-using-glcreatebuffers).

**Comment by pramathe** [comment]
Ok, that fits. While finding out my OpenGL version I recognized that the onboard graphics card of my laptop (Intel HD 630) was globally active. My actual drivers for that support OpenGL 4.4. Now I switched to my additional NVIDIA GeForce GTX 950M, supporting OpenGL 4.6 and the problem disappeared.
Thanks for clarifying that! :)
But I guess the user should be informed by MegaMol about that issue, instead of beeing confronted with a crash without error promting!?
